addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  global:
    - PROJECT="{{ Project Name }}"
    - VERSION="{{ Version }}"
    - RELEASE="{{ Release }}"
    - BRANCH_PROD="master"
    - BRANCH_DOC="gh-pages"
    - TESTS="0"
    - LINT="0"
    - DOCS="0"
    - DOCS_PY_VERSION="2.7"
    - PYPI="0"
    # Use this to map to external Sphinx sources. Format is a comma separated
    # list of name, uri pairs - or just a URI. In the event of just URIs, the
    # old format will be used. Example:
    #  INTERSPHINX="requests=http://docs.python-requests.org/"
    # would be the same as:
    #   INTERSPHINX="http://docs.python-requests.org/"
    - INTERSPHINX=""
    # Generate this per repo with the following:
    #   travis encrypt 'PYPI_PASSWORD="$PYPI_PASSWORD"'-r LasLabs/repo-name
    - secure: "$PYPI_TOKEN"
  matrix:
    - TESTS="1"
    - PYPI="1"
    - DOCS="1"
    - LINT="1"

install:
  - git clone --depth=1 https://github.com/LasLabs/python-quality-tools.git ${HOME}/python-quality-tools
  - export PATH=${HOME}/python-quality-tools/travis:${PATH}
  - travis_install

script:
  - travis_run

after_success:
  - travis_after_success
