#!/usr/bin/env bash
#
# Copyright 2016 LasLabs Inc.
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).

# Always install package and requirements
if [ -f test_requirements.txt ]; 
then
  pip install -r ./test_requirements.txt
  
elif [ -f requirements.txt ];
then
  pip install -r ./requirements.txt
fi

pip install .

# Now do the independent actions
if [ "${LINT_CHECK}" = "1" ]; 
then

  . travis_install_lint

elif [ "${TESTS}" = "1" ]; 
then

  . travis_install_test

elif [ "${DOCS}" = "1" ] || [ "${PYPI}" = "1" ];
then

  if [ "${TRAVIS_BRANCH}" = "${BRANCH_PROD:=master}" ] \
  && [ "${TRAVIS_PULL_REQUEST}" = "false" ];
  then

    . travis_install_doc

  fi

fi
