#!/usr/bin/env bash
#
# Copyright 2016 LasLabs Inc.
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).

set -e

if [ "${DOCS_SEPARATE_PAGE}" = "1" ];
then
    sphinx-apidoc -f -F -P -a --separate -o docs/ ./;
else
    sphinx-apidoc -f -F -P -a -o docs/ ./;
fi

cp ${HOME}/python-quality-tools/sphinx/* ./docs
cd ./docs/

make html
